name: "Release Fount"

on:
  push:
    tags:
      - "v*" # This will trigger the workflow when you push a tag that starts with 'v'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform == 'macos-latest' && 'macos-15' || matrix.platform }}
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Install protoc
        if: matrix.platform == 'macos-latest'
        run: brew install protobuf

      - name: Install protoc
        if: matrix.platform == 'windows-latest'
        run: choco install protoc

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        shell: bash
        run: pnpm install

      - name: Build frontend
        shell: bash
        run: pnpm build

      - name: Check and Install Metal Toolchain
        if: matrix.platform == 'macos-latest'
        run: |
          echo "Xcode version:"
          xcodebuild -version
          echo "Metal toolchain version:"
          xcodebuild -downloadComponent MetalToolchain -exportPath /tmp/metalToolchainDownload/
          xcodebuild -importComponent MetalToolchain -importPath /tmp/metalToolchainDownload/*.exportedBundle
          echo "Metal version:"
          metal -v

      - name: Verify macOS build environment
        if: matrix.platform == 'macos-latest'
        run: |
          echo "Xcode version:"
          xcodebuild -version
          echo "CMake version:"
          cmake --version || echo "CMake not found - will be installed by mlx-sys"

      - name: Set Metal compilation flags
        if: matrix.platform == 'macos-latest'
        run: |
          echo "CMAKE_METAL_FLAGS=-std=macos-metal2.3" >> $GITHUB_ENV
          echo "METAL_LANGUAGE_VERSION=metal2.3" >> $GITHUB_ENV
          echo "CMAKE_OSX_DEPLOYMENT_TARGET=13.0" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=13.0" >> $GITHUB_ENV

      - name: import Apple Developer Certificate
        if: matrix.platform == 'macos-latest'
        # Prevents keychain from locking automatically for 3600 seconds.
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security find-identity -v -p codesigning build.keychain

      - name: verify certificate
        if: matrix.platform == 'macos-latest'
        run: |
          CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application")
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
          echo "Certificate imported."
      - uses: tauri-apps/tauri-action@v0
        env:
          # Use a PAT with repo scope for cross-repo access
          GITHUB_TOKEN: ${{ secrets.CROSS_REPO_PAT }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ env.CERT_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Fount ${{ github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          includeUpdaterJson: true
          releaseDraft: true
          args: ${{ matrix.args }}
          # Specify the public repository where releases should be published
          owner: fount-labs # Replace with your GitHub username or organization
          repo: fount # Replace with your public repository name
          releaseCommitish: main
